name: build

# Github Actions aren't supporting anchors yet
# upvote here https://github.com/github/feedback/discussions/4501

on: 
  push:
  pull_request:
    branches:
      - master
  # activating dispatch to allow manual runs
  # workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v3
      - name: Build on Windows
        run: |
          .\build.cmd
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: teos-${{ matrix.os }}
          path: |
            teos.pce
            TBED/**/*.*
            LICENSE.TXT
            LICENSE_1_0.TXT
            README.md


  publish_package:
    runs-on: ubuntu-latest
    needs: [build]
    #if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    steps:
      - name: Check out code from the repository
        uses: actions/checkout@v3
      - name: Get previoulsy built artifacts win64
        uses: actions/download-artifact@v3
        with:
          name: teos-windows-2022
          path: teos-windows-2022
      - name: publish package
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          rm: true # do not keep old latest artifacts
          files: |
            teos-windows-2022/*

